name: Update tldr commands file

on:
  push:
    branches:
      - master
  schedule:
    - cron:  '0 0 * * *'

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python Environment
        uses: actions/setup-python@v5

      - name: Install Requirements
        run: pip install -r ./tldrdict/requirements.txt

      - name: Execute get pages and version zips
        run: |
          cd tldrdict
          python update.py
          sudo apt install moreutils
          ./update_pages.sh

      - name: setup git config
        run: |
          git config user.name ${{ secrets.USERNAME }}
          git config user.email ${{ secrets.EMAIL }}

      - name: commit changes
        run: |
          ./tldrdict/commit.sh
